-- Add 10 curated catalog exercises (30 total with existing seed)
INSERT INTO "ExerciseCatalog" ("slug", "nameEs", "nameEn", "descriptionEs", "descriptionEn", "muscleGroup", "mediaType", "mediaUrl", "sortOrder", "updatedAt") VALUES
('dumbbell-bench-press', 'Press de banca con mancuernas', 'Dumbbell bench press', 'Acuéstate en el banco y empuja las mancuernas desde el pecho hasta extender codos.', 'Lie on the bench and press the dumbbells from chest level to full elbow extension.', 'CHEST', 'GIF', NULL, 210, CURRENT_TIMESTAMP),
('cable-fly', 'Aperturas en polea', 'Cable fly', 'Con brazos semiflexionados, junta las manos al frente apretando el pecho.', 'With soft elbows, bring your hands together in front while squeezing the chest.', 'CHEST', 'GIF', NULL, 220, CURRENT_TIMESTAMP),
('seated-cable-row', 'Remo en polea sentado', 'Seated cable row', 'Tira del agarre hacia el abdomen manteniendo el torso estable.', 'Pull the handle toward your abdomen while keeping your torso stable.', 'BACK', 'GIF', NULL, 230, CURRENT_TIMESTAMP),
('dumbbell-shoulder-press', 'Press de hombro con mancuernas', 'Dumbbell shoulder press', 'Empuja las mancuernas por encima de la cabeza sin arquear la espalda.', 'Press the dumbbells overhead without excessive lower-back arch.', 'SHOULDERS', 'GIF', NULL, 240, CURRENT_TIMESTAMP),
('hammer-curl', 'Curl martillo', 'Hammer curl', 'Flexiona los codos con agarre neutro, subiendo las mancuernas a los hombros.', 'Curl with a neutral grip, bringing dumbbells up toward your shoulders.', 'ARMS', 'GIF', NULL, 250, CURRENT_TIMESTAMP),
('skull-crusher', 'Press francés', 'Skull crusher', 'Desde brazos extendidos, flexiona codos bajando la barra hacia la frente.', 'From extended arms, bend elbows lowering the bar toward your forehead.', 'ARMS', 'GIF', NULL, 260, CURRENT_TIMESTAMP),
('leg-curl', 'Curl femoral', 'Leg curl', 'Flexiona rodillas llevando el talón hacia el glúteo de forma controlada.', 'Curl your heels toward your glutes under control.', 'LEGS', 'GIF', NULL, 270, CURRENT_TIMESTAMP),
('leg-extension', 'Extensión de cuádriceps', 'Leg extension', 'Extiende rodillas desde el asiento sin rebotar arriba.', 'Extend your knees from the seat without bouncing at the top.', 'LEGS', 'GIF', NULL, 280, CURRENT_TIMESTAMP),
('bulgarian-split-squat', 'Sentadilla búlgara', 'Bulgarian split squat', 'Pie trasero elevado, baja la rodilla delantera y empuja para subir.', 'Rear foot elevated, lower the front knee and drive up.', 'LEGS', 'GIF', NULL, 290, CURRENT_TIMESTAMP),
('hanging-leg-raise', 'Elevación de piernas colgado', 'Hanging leg raise', 'Colgado de la barra, eleva piernas o rodillas controlando la bajada.', 'Hang from the bar and raise legs or knees with a controlled descent.', 'CORE', 'GIF', NULL, 300, CURRENT_TIMESTAMP);
